import { InsertProduct, InsertCategory } from '@shared/schema';
import { hashPassword } from '../server/auth';

export const sampleCategories: InsertCategory[] = [
  { name: "Ladies", parentId: null, slug: "ladies" },
  { name: "Men", parentId: null, slug: "men" },
  { name: "Kids", parentId: null, slug: "kids" },
  { name: "Home", parentId: null, slug: "home" },
  { name: "Shirts & Blouses", parentId: 1, slug: "shirts-blouses" },
  { name: "Linen Shirts", parentId: 1, slug: "linen-shirts" },
  { name: "Shirts", parentId: 1, slug: "shirts" },
  { name: "Blouses", parentId: 1, slug: "blouses" },
  { name: "Denim Shirts", parentId: 1, slug: "denim-shirts" },
];

export const sampleProducts: InsertProduct[] = [
  {
    name: "Printed linen-blend shirt",
    description: "A stylish printed linen-blend shirt perfect for any occasion.",
    price: 1499.00,
    category: "ladies",
    subcategory: "linen-shirts",
    imageUrl: "https://image.hm.com/assets/hm/ce/72/ce722545587b01c07aa14ebf1af57c93776372a8.jpg",
    inStock: true,
  },
  {
    name: "Printed mini skirt",
    description: "A fashionable printed mini skirt for a trendy look.",
    price: 1299.00,
    category: "ladies",
    subcategory: "skirts",
    imageUrl: "https://image.hm.com/assets/hm/9d/f3/9df3167cc6bb821fe236013766adf842b049d142.jpg",
    inStock: true,
  },
  {
    name: "Scalloped mini dress",
    description: "An elegant scalloped mini dress for special occasions.",
    price: 1999.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://image.hm.com/assets/hm/d1/fa/d1faeb012a403ccc01d6be4305d909bdb33a47f8.jpg",
    inStock: true,
  },
  {
    name: "Cotton Embroidered Blouse",
    description: "A light cotton blouse with embroidered details.",
    price: 1299.00,
    category: "ladies",
    subcategory: "blouses",
    imageUrl: "https://unsplash.com/photos/H8uf5ua5uW4/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQ0ODYwOTgxfA&force=true",
    inStock: true,
  },
  {
    name: "Floral Print Blouse",
    description: "A floral print blouse perfect for summer.",
    price: 1499.00,
    category: "ladies",
    subcategory: "blouses",
    imageUrl: "https://unsplash.com/photos/3I_aBm_xbkw/download?force=true",
    inStock: true,
  },
  {
    name: "Lace-back Cotton Blouse",
    description: "A cotton blouse with a beautiful lace back detail.",
    price: 1799.00,
    category: "ladies",
    subcategory: "blouses",
    imageUrl: "https://unsplash.com/photos/p5C3Ur0HciM/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQ0ODYxMDc4fA&force=true",
    inStock: true,
  },
  {
    name: "Oversized Linen Shirt",
    description: "A comfortable oversized linen shirt.",
    price: 1999.00,
    category: "ladies",
    subcategory: "linen-shirts",
    imageUrl: "https://unsplash.com/photos/u_qeBMfHCbg/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8Mnx8TGluZW4lMjBTaGlydHxlbnwwfHx8fDE3NDQ4NjEwOTd8MA&force=true",
    inStock: true,
  },
  {
    name: "Striped Cotton Blouse",
    description: "A light striped cotton blouse with a classic collar.",
    price: 1399.00,
    category: "ladies",
    subcategory: "blouses",
    imageUrl: "https://images.unsplash.com/photo-1589810635657-232948472d98?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
    inStock: true,
  },
  {
    name: "Floral Print Scarf",
    description: "A beautiful floral print scarf to complement your outfit.",
    price: 899.00,
    category: "ladies",
    subcategory: "accessories",
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
    inStock: true,
  },
  {
    name: "Red Sleeveless Dress",
    description: "A stunning red sleeveless dress for special occasions.",
    price: 2499.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://unsplash.com/photos/I_a57bVkkw4/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8Mnx8UmVkJTIwU2xlZXZlbGVzcyUyMERyZXNzfGVufDB8fHx8MTc0NDg2MTEzNHww&force=true",
    inStock: true,
  },
  {
    name: "Red Puff Sleeve Dress",
    description: "An elegant red dress with puff sleeves.",
    price: 2699.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://images.unsplash.com/photo-1580651214613-f4692d6d138f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
    inStock: true,
  },
  {
    name: "Red Ruffle Dress",
    description: "A beautiful red ruffle dress for special occasions.",
    price: 2599.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://images.unsplash.com/photo-1551048632-24e444b48a3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
    inStock: true,
  },
  {
    name: "White Cotton Shirt",
    description: "A crisp white cotton shirt, a wardrobe essential.",
    price: 1599.00,
    category: "ladies",
    subcategory: "shirts",
    imageUrl: "https://unsplash.com/photos/R570zdM32J0/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8MTB8fFJlZCUyMFNsZWV2ZWxlc3MlMjBEcmVzc3xlbnwwfHx8fDE3NDQ4NjExMzR8MA&force=true",
    inStock: true,
  },
  {
    name: "Denim Button-Up Shirt",
    description: "A classic denim button-up shirt.",
    price: 1999.00,
    category: "ladies",
    subcategory: "denim-shirts",
    imageUrl: "https://images.unsplash.com/photo-1589810635657-232948472d98?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
    inStock: true,
  },
  {
    name: "Linen Blend Shirt",
    description: "A comfortable linen blend shirt perfect for summer.",
    price: 1799.00,
    category: "ladies",
    subcategory: "linen-shirts",
    imageUrl: "https://unsplash.com/photos/rpwaDdp0agg/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQ0ODYxMDEwfA&force=true",
    inStock: true,
  }
];

export const newInProducts: InsertProduct[] = [
  {
    name: "Broderie anglaise dress",
    description: "A beautiful broderie anglaise dress with delicate detailing.",
    price: 2499.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://image.hm.com/assets/hm/7a/d5/7ad5c9917ae0114b6dcfcba93df4a9e1182ff0dd.jpg",
    inStock: true,
  },
  {
    name: "Oversized T-shirt",
    description: "A comfortable oversized t-shirt for casual wear.",
    price: 799.00,
    category: "ladies",
    subcategory: "t-shirts",
    imageUrl: "https://image.hm.com/assets/hm/98/1a/981aa526a27f2ea98ad60a547805217bafe24b89.jpg",
    inStock: true,
  },
  {
    name: "Poplin maxi skirt",
    description: "An elegant poplin maxi skirt for a sophisticated look.",
    price: 1999.00,
    category: "ladies",
    subcategory: "skirts",
    imageUrl: "https://image.hm.com/assets/hm/5a/9e/5a9ecd40f003bf10e1656cd1264f1308085aff54.jpg",
    inStock: true,
  },
  {
    name: "Cropped poplin top",
    description: "A stylish cropped poplin top perfect for summer.",
    price: 1299.00,
    category: "ladies",
    subcategory: "tops",
    imageUrl: "https://image.hm.com/assets/hm/b9/54/b954598aa2c2324c33ed29672ad367573e9f7046.jpg",
    inStock: true,
  },
  {
    name: "Printed satin scarf",
    description: "A luxurious printed satin scarf to elevate any outfit.",
    price: 899.00,
    category: "ladies",
    subcategory: "accessories",
    imageUrl: "https://image.hm.com/assets/hm/f3/8a/f38ad697361b02e423993c883db347f2b757b98a.jpg",
    inStock: true,
  },
  {
    name: "Bow-back dress",
    description: "An elegant dress with a beautiful bow detail at the back.",
    price: 2299.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://image.hm.com/assets/hm/08/d0/08d034e94db78663ffc9ca9d1ab138f787bf83dc.jpg",
    inStock: true,
  },
  {
    name: "Broderie anglaise-detail dress",
    description: "A stunning dress with broderie anglaise detailing.",
    price: 2699.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://image.hm.com/assets/hm/f3/17/f3176f33f09c1dccfbf05126d665cc185575d386.jpg",
    inStock: true,
  },
  {
    name: "Broderie anglaise-sleeved dress",
    description: "A charming dress with broderie anglaise sleeves.",
    price: 2499.00,
    category: "ladies",
    subcategory: "dresses",
    imageUrl: "https://image.hm.com/assets/hm/13/5f/135f111c73b65873cc5272bfaa99ab572e768070.jpg",
    inStock: true,
  },
  {
    name: "Linen-blend trousers",
    description: "Comfortable and stylish linen-blend trousers.",
    price: 1799.00,
    category: "ladies",
    subcategory: "trousers",
    imageUrl: "https://image.hm.com/assets/hm/bf/54/bf54e0a9ba3e30ffebbf2cd28bd336ef7e8083ea.jpg",
    inStock: true,
  }
];

export const adminUser = {
  username: "admin",
  password: await hashPassword("admin123"),
  email: "admin@example.com",
  role: "admin"
};